#              _    _
#             | |  | |
#  _ __   ___ | |__| |_   _ _ __   __ _  ___ _ __
# | '_ \ / _ \|  __  | | | | '_ \ / _` |/ _ \ '__|
# | | | | (_) | |  | | |_| | | | | (_| |  __/ |
# |_|_|_|\___/|_|  |_|\__,_|_|_|_|\__, |\___|_|
# |  _ \            /\       | |   __/ |    | |
# | |_) |_   _     /  \   ___| |__|___/_  __| | ___  _ __
# |  _ <| | | |   / /\ \ / __| '_ \ / _ \/ _` |/ _ \| '_ \
# | |_) | |_| |  / ____ \ (__| | | |  __/ (_| | (_) | | | |
# |____/ \__, | /_/    \_\___|_| |_|\___|\__,_|\___/|_| |_|
#         __/ |
#        |___/


# Setup world where noHunger will be enable
World:
  - world